trigger:
- master

jobs:
- job: Xcode10_2
  pool:
    vmImage: 'macos-latest'
  steps:
  - bash: Tests/test_xcodebuild.sh Xcode_10.2.1
    env:
      IOS_DEVICE: 'platform=iOS Simulator,OS=12.2,name=iPhone SE'
      TVOS_DEVICE: 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K'
      CODECOV_JOB: 'true'
      CODECOV_TOKEN: $(codecovToken)
