trigger:
- master

jobs:
- job: Xcode11
  pool:
    vmImage: 'macos-latest'
  steps:
  - bash: Tests/test_xcodebuild.sh Xcode_11.4
    env:
      IOS_DEVICE: 'platform=iOS Simulator,OS=13.4,name=iPhone 11'
